services:
  pgdatabase:
    image: pgvector/pgvector:0.7.4-pg16
    environment:
      - POSTGRES_USER=${PGVECTOR_USER:-postgres}
      - POSTGRES_PASSWORD=${PGVECTOR_PASSWORD:-postgres}
      - POSTGRES_DB=${PGVECTOR_DATABASE:-brevia}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${PGVECTOR_PORT:-5432}:5432
  pgadmin:
    image: dpage/pgadmin4
    profiles: ["admin", "fullstack"]
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-4000}:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
  breviaapi:
    image: ghcr.io/brevia-ai/brevia
    profiles: ["api", "fullstack"]
    environment:
      - PGVECTOR_HOST=pgdatabase
      - PGVECTOR_PORT=5432
      - PGVECTOR_DATABASE=${PGVECTOR_DATABASE:-brevia}
      - PGVECTOR_USER=${PGVECTOR_USER:-postgres}
      - PGVECTOR_PASSWORD=${PGVECTOR_PASSWORD:-postgres}
      - BREVIA_ENV_SECRETS=${BREVIA_ENV_SECRETS:-{}}
    ports:
      - "${BREVIA_API_PORT:-8000}:8000"
    volumes:
      - breviaapidata:/var/lib/breviaapi
  breviaapp:
    image: ghcr.io/brevia-ai/brevia-app
    profiles: ["fullstack"]
    environment:
      - NUXT_API_BASE_URL=http://breviaapi:8000
    ports:
      - "${BREVIA_APP_PORT:-3000}:3000"
    volumes:
      - breviaappdata:/var/lib/breviaapp

volumes:
  pgdata:
    name: ${PGVECTOR_VOLUME_NAME:-pgdata}
  pgadmindata:
    name: ${PGADMIN_VOLUME_NAME:-pgadmindata}
  breviaappdata:
    name: ${BREVIA_APP_VOLUME_NAME:-breviaapp}
  breviaapidata:
    name: ${BREVIA_API_VOLUME_NAME:-breviaapi}
