version: '3.9'
services:
    pgdatabase:
        image: ankane/pgvector
        environment:
            - POSTGRES_USER=${PGVECTOR_USER}
            - POSTGRES_PASSWORD=${PGVECTOR_PASSWORD}
            - POSTGRES_DB=${PGVECTOR_DATABASE}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "${PGVECTOR_PORT}:5432"
    pgadmin:
        image: dpage/pgadmin4
        profiles: ["admin"]
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "${PGADMIN_PORT}:80"
        volumes:
          - pgadmindata:/var/lib/pgadmin
volumes:
  pgdata:
    name: ${PGVECTOR_VOLUME_NAME}
  pgadmindata:
    name: ${PGADMIN_VOLUME_NAME}
