site_name: Brevia Docs
repo_url: https://github.com/brevia-ai/brevia
dev_addr: "127.0.0.1:8001"
theme:
  name: material
  logo: assets/brevia-logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brevia-ai/brevia
    - icon: fontawesome/solid/globe
      link: https://atlasconsulting.it
    - icon: fontawesome/brands/linkedin
      link: https://it.linkedin.com/company/atlas-srl

nav:
  - Brevia: index.md
  - Setup: setup.md
  - Configuration:
     - Global configuration: config.md
     - Collection configuration: collection_config.md
  - Models:
    - Overview: models/overview.md
    - OpenAI: models/openai.md
    - Cohere: models/cohere.md
    - Ollama: models/other_models.md
  - Security: security.md
  - Tutorials:
    - Create Simple RAG: tutorials/create_collection.md
    - Create Summarization Analysis: tutorials/create_summarization.md
    - Create Custom Services: tutorials/create_custom_services.md
  - Database: database.md
  - Collections: collections.md
  # /index/... endpoints
  - Document Index: document_index.md
  # /chat, /search, /chat_history
  - Chat and search: chat_search.md
  # /summarize, upload, generic service, /transcribe...
  - Analyze services: analyze_services.md
  - Async jobs: async_jobs.md
  - Endpoints Overview: endpoints_overview.md
  - Reference:
    - REST API Reference:  redoc/
