site_name: Brevia Docs
theme:
  name: material

nav:
  - Brevia: index.md
  - Setup: setup.md
  - Configuration: config.md
  - Security: security.md
  - Tutorials:
    - Create Simple RAG: tutorials/create_collection.md
    - Create Summarization Analysis: tutorials/create_summarization.md
    - Create Custom Services: tutorials/create_custom_services.md
  - Database: database.md
  - Collections: collections.md
  # /index/... endpoints
  - Document Index: document_index.md
  # /chat, /search, /chat_history
  - Chat and search: chat_search.md
  # /summarize, upload, generci service, /transcribe...
  - Analyze services: analyze_services.md
  - Async jobs: async_jobs.md
  - Models:
    - OpenAI: models/openai.md
    - Cohere: models/cohere.md
    - Other Models: models/other_models.md
  - Endpoints Overview: endpoints_overview.md
  - Reference:
    - REST API Reference:  redoc/
